### ISSUE TITLE
Where to add Claude API key?

### ISSUE THREAD

**Issue by RussellCardiff** [Talamantez/claude-vscode#23] opened 2024-12-12 11:10 UTC
Hi, trying out your extension but can't find the setting for the api key. All I can find is the Model setting.

![image](https://github.com/user-attachments/assets/21c9edc4-e903-49e1-9d8e-1bfffc5edf1f)

**Comment by Talamantez** [comment] 2024-12-17 02:08
Hi Russell - Thanks for reaching out with this issue.  I am unable to reproduce the error with the current version of the app.  Can you let me know your platform?  Also please make sure you are using the current version 2.1.8.  If this is all in place, please uninstall and reinstall the extension.  If that doesn't resolve your issue, you can try running VSCode with no extensions (code --disable-extensions), then install the extension. This will make sure that there are no conflicts with other extensions. If this doesn't resolve your issue, try updating or reinstalling vscode.  Please let me know after taking these steps if it resolves the issue or not.  Rest assured, we'll get you up and running.

![image](https://github.com/user-attachments/assets/0604f1c9-c324-411d-b3c2-caa8f217d080)

Steps to choose specific version:
Claude AI Assistant > choose gear icon > choose "Install specific version..."
![install specific](https://github.com/user-attachments/assets/1753cbc7-3cad-407e-921f-b1d15eac0cce)

Choose 2.1.8:
![choose 2 1 8](https://github.com/user-attachments/assets/e57a6f3e-c852-452d-82bf-ecc870a2e913)

**Comment by Talamantez** [comment] 2024-12-22 05:10
It's been 5 days since responding to this ticket, so I'll close it. Please feel free to open another if you continue to have issues, and I will do my best to help you out. Thank you!

**Closed by Talamantez** 2024-12-22 05:10 UTC
